### ISSUE TITLE
Packed Pixel Format support

### ISSUE THREAD

**Issue by jvieira88** [genicam/harvesters#167]
Hi,
I'm working with a SVS-Vistek Exo camera which supports Mono12Packed pixels. The camera works fine with Mono8 but as soon as I try Mono12Packed it fails. Looking at the Harvesters documentation, it says it doesn't support packed formats.

Is there a plan to implement this feature in a foreseeable future? If not, could someone point me in the direction of where this would be implemented in the code?

Regards,
Joao

**Comment by kazunarikudo** [comment]
@jvieira88 Hi. Could you tell me how did it fail? /Kazunari

**Comment by jvieira88** [comment]
With the pixel format set to 'Mono12Packed', whenever I try to do an image acquisition with:
`buffer = self.m_oImageAcq.fetch_buffer()
component = buffer.payload.components[0]
m_arrLastFrame = component.data.reshape(component.height, component.width)`

I get an AttributeError Exception `'NoneType' object has no attribute 'data'`. This comes from the component object which seems to be None.

Joao

**Comment by kazunarikudo** [comment]
@jvieira88 Thanks. Okay, so could you tell me the version number? You can get the version number with the following code:
```
import harvesters
print(harvesters.__version__)
```

**Comment by jvieira88** [comment]
@kazunarikudo It's showing version 1.0.5. 
I can see the latest version is 1.2.3. I also have the GUI,  wonder if it caused the downgrade.

**Comment by kazunarikudo** [comment]
@jvieira88 Thank you for the update. Okay, I see your situation. I have pinned the Harvester version that is consumed by Harvester GUI due to a compatibility issue around version 1.2. At version 1.2.3, I (think I) have supported packed pixel formats but have not updated Harvester GUI so that it works with Harvester 1.2.3. I would like to update Harvester GUI but the expected date would not be close as you expect because Harvester is one of my private OSS projects so the time I can work for it is very limited. It is totally okay to edit Harvester GUI by yourself. In the meantime, I would work for it and I will let you know once such a version is released. Sorry for the inconvenience.

**Comment by jvieira88** [comment]
@kazunarikudo Thanks for your quick reply. I tried with version 1.2.3 but got the same error. 
Totally get your situation, I just thank you for using your free time to do this. It's a really good project and useful for many people.
I'm not using the GUI so much now, and would prefer to use the harvester library but having support for packed 12 bit pixels would be great for me.
Do you think you'd get a chance to look at this? I was looking at the last commits but couldn't find the part of the code where this is handled.

**Comment by jvieira88** [comment]
@kazunarikudo Thanks for your quick reply. I tried with version 1.2.3 but got the same error. 
Totally get your situation, I just thank you for using your free time to do this. It's a really good project and useful for many people.
I'm not using the GUI so much now, and would prefer to use the harvester library but having support for packed 12 bit pixels would be great for me.
Do you think you'd get a chance to look at this? I was looking at the last commits but couldn't find the part of the code where this is handled.

**Comment by kazunarikudo** [comment]
@jvieira88 I was trying to support packed formats with the change at commit c2705031aef78294477beb5b66c957d061e849cb and commit 9bc5b8b6df6db80271c9652ecc9f4d711d480eb5. I would appreciate it if you could find a clue that I can infer the root cause because I do not have any device that I can try real Mono12Packed format here.

**Comment by jvieira88** [comment]
@kazunarikudo Thanks. I'll have a look into it next week I hope! :)

**Comment by jvieira88** [comment]
@kazunarikudo I was trying to push the fix but keep getting an error from git. Could you give me write access rights?

**Comment by kazunarikudo** [comment]
@jvieira88 Thank you for your message. Could you fork harvester and create a pull request, please? We are running as the committee so it's a bit picky on privileges. I hope you understand our decision. I'll be waiting for your pull request. Thanks! /Kazunari

**Comment by mawillia** [comment]
Hi @kazunarikudo.  I am looking at your patch for this and you are using "Mono12Packed" for the name matching.  Doesn't the PFNC require "Mono12p" for this packing scheme?  (At least I am reading version 2.0).  We have a camera supporting Mono12p (Mono12 with packing) and the 1.2.6 harvester gives me the same results as reported here.

**Comment by jvieira88** [comment]
Hi @mawillia , this issue has been addressed in version 1.2.6. I have a camera here and it's working.
Did you set the target device format as `'Mono12Packed'`? Example:
```
oNode = self.m_oImageAcq.remote_device.node_map
oNode.Width.value = 1920
oNode.Height.value = 1200
oNode.PixelFormat.value = 'Mono12Packed'
```

**Comment by mawillia** [comment]
Hi @kazunarikudo, the camera is reporting "Mono12p" (per the EMVA PFNC) as the supported Format, not Mono12Packed.  If I try to set the PixelFormat.value to "Mono12Packed" I get an exception.  Mono12p and Mono12Packed are not the same.  I believe Mono12Packed is a GigE Vision specific format, the bits are not packed the same way as Mono12p, which is used for U3V protocols and is a PFNC standard name.

**Comment by kazunarikudo** [comment]
@mawillia Could you try out the latest commit in the master branch, please?

**Comment by mawillia** [comment]
Hi @kazunarikudo the master branch works now with "Mono12p" and our camera.

Thanks!

**Comment by kazunarikudo** [comment]
@mawillia Hi, Michael. Thank you for letting me know the result. I'm glad to hear that. {I'm planning to improve the design so that Harvester does not overlook the pixel formats that I have implemented.}
